### ISSUE TITLE
Unbound Local Error

### ISSUE THREAD

**Issue by EgemenGames603** [FlashChaser/Open-Source-Battle-Bot#23]
![image](https://user-images.githubusercontent.com/49919491/58044641-8de18000-7b40-11e9-8f0a-30ba072b3031.png)

What do I do?

**Comment by SuicideBooth** [comment]
is that in python?

**Comment by EgemenGames603** [comment]
It's the filed called "windows.exe"

**Comment by SuicideBooth** [comment]
ya that doesn't work for me either. I'm trying to make it work on python but I got no clue how to use it sadly.

**Comment by EgemenGames603** [comment]
When I go on dokkan.py it closes automatically..

**Comment by FlashChaser** [comment]
Need more information as to what you were doing at the time. If the game was in maintenance it can cause this. 

Someone needs to implement an error check for maintenance which can prevent this and provide more context for users.

**Comment by marcgarc** [comment]
Hi!

There is no maintenance, it's an error that shows up when the program tries to recover the Stamina when {'code': 'act_is_not_enough'}

However, it also says 'STAMINA RESTORED' but it isn't.

Hope this helps.

**Comment by FlashChaser** [comment]
This has been fixed with the latest code

**Comment by marcgarc** [comment]
I have downloaded version 0.1.0 and it still shows, both with the dokkan.py and the .exe. If there's any feedback I can provide I'd be happy to help :)
